#parameters  go in the right-hand side
schema: schema_name_in_db
suffix: "yearnumber"

#table names
db_tables:
  table1: the_real_table_name_shown_in_databse{suffix}
  table2: another_table_name_shown_in_database{suffix}

#Some flat files used as an input if they are not in the database
name_program_uses: ../location_folder/file_name.csv

paths:
  output: ../foldername_where_you_want_to_save_the_outputs/
  sql_path: ../folder_for_sql_files/
  data_path: ../folder_for_downloading_data/

#business_rules: making dictionaries to store data values. key:value
##scienario1
bucketing_data_values_dict: {
  "type1": "data_field1= value1" AND data_field2=value_b",
  "type2": "data_field1= value2" AND data_field2=value_a"
}

##scienario2
comparison:
  pair1: [type1, type2]
  
##scienario3
continuous_field:
- DE1
- DE2
- DE3
continuous_field_dict: {
  "DE1": 0,
  "DE2": 1,
  "DE3": 0
}
categorical_field:
- DE4
- DE5
- DE6

unique_identifier:
- DE0

#scienario4- subset condition based on sql
subsets:
  Sub_population_name:
    slice_name: Subpopulation name
    filename: sub_population_name.csv
    where: ../sql/sub_population_name.sql
    field_list: ["slice_DE_1", "slice_DE_2"]
    field: "slice_DE_1"


